package hr.fer.zemris.java.hw05.db;

public enum QueryTokenType {

	/**
	 * Tokens of this type represent a field name in the conditional expression, 
	 * such as "jmbag", "firstName", "lastName" or "finalGrade".
	 */
	FIELD_NAME,
	
	/**
	 * Tokens of this type represent a comparison operator of the conditional
	 * expression, such as "<", "<=", "=", "!=", ">", ">=" or "LIKE".
	 */
	COMPARISON_OPERATOR,
	
	/**
	 * Tokens of this type represent a string literal of the conditional
	 * expression. No escaping is allowed in such literals, and a single
	 * wildcard '*' is allowed, but only if used in conjecture with the 
	 * conditional operator "LIKE".
	 */
	STRING_LITERAL,
	
	/**
	 * Tokens of this type represent a logical operator that is used to 
	 * combine the conditional expressions. Currently, the only supported
	 * logical operator is "AND". Operator is case-insensitive, so tokens
	 * of this type will have their value capitalized.
	 */
	LOGICAL_OPERATOR,
	
	/**
	 * Token of this type is the last token generated by the lexer. It 
	 * denotes that the end of query is reached and there is no more information
	 * to process. Value of tokens with this type should be <code>null</code>.
	 */
	EOF,
	
	/**
	 * Tokens of this type represent undefined parts of the query. If tokens
	 * of this type are extracted from the query, then the query is 
	 * invalid and an appropriate exception will be thrown.
	 */
	OTHER;
	
}